### ISSUE TITLE
请问一下有MCU的基本信息吗

### ISSUE THREAD

**Issue by JunnanLi** [T-head-Semi/wujian100_open#20]
@mballackh13 
您好，请问一下有MCU的基本信息吗？例如，几级流水线，多少发射，是否支持乱序，FPGA上可综合频率，资源开销等。

**Comment by xqbumu** [comment]
https://www.t-head.cn/file/download?spm=a2ouz.12987056.0.0.305648abfxjDVq&file=1571624106073/T-Head%20Tools%20package.zip

里面有文档

**Comment by JunnanLi** [comment]
您好，


不好意思，我在压缩包里只发现了T-Head DebugServer-V5.8.6， T-Head RISC-V Toolchain-V1.2.2，T-Head CDK-windows-V1.18.10-20191018-1527。
请问一下，相关的文档是指？





--

厉俊男
国防科技大学     计算机学院


Li Junnan
College of Computer Science, National University of Defense Technology

在 2019-10-25 18:21:14，"卜木" <notifications@github.com> 写道：


https://www.t-head.cn/file/download?spm=a2ouz.12987056.0.0.305648abfxjDVq&file=1571624106073/T-Head%20Tools%20package.zip

里面有文档

**Comment by wanermian** [comment]
> @mballackh13
> 您好，请问一下有MCU的基本信息吗？例如，几级流水线，多少发射，是否支持乱序，FPGA上可综合频率，资源开销等。

https://www.t-head.cn/product/e902?spm=a2ouz.12987052.0.0.511748abk5lBa2

**Comment by mballackh13** [comment]
基本信息在用户手册中有具体描述
