### ISSUE TITLE
Failed to load program while simulating

### ISSUE THREAD

**Issue by shenfanML** [T-head-Semi/wujian100_open#21]
> WARNING: File inst.pat referenced on E:/RiscV/wujian100/wujian100/wujian100.srcs/sim_1/imports/tb/tb.v at line 256 cannot be opened for reading. Please ensure that this file is available in the current working directory.
> ######time:                   0, Dump start######
> 	******START TO LOAD PROGRAM******
> 
> WARNING: File data.pat referenced on E:/RiscV/wujian100/wujian100/wujian100.srcs/sim_1/imports/tb/tb.v at line 275 cannot be opened for reading. Please ensure that this file is available in the current working directory.
> run: Time (s): cpu = 00:00:08 ; elapsed = 00:00:38 . Memory (MB): peak = 1899.332 ; gain = 0.000
> 
As the problems showed in the quotes， how can I get the files  inst.pat and data.pat?

**Comment by mballackh13** [comment]
Delete all temp file and checkout the newest code then try again. I think it will be well.

**Comment by shenfanML** [comment]
> 
> 
> Delete all temp file and checkout the newest code then try again. I think it will be well.

I git clone the latest code(20191027.12.01), and build a new vivado project, but it reported the same problem as below: 

> INFO: [Simtcl 6-17] Simulation restarted
> run 1 ms
> WARNING: File test.pat referenced on E:/RiscV/wujian100/wujian100_vivado/wujian100.srcs/sim_1/imports/tb/tb.v at line 260 cannot be opened for reading. Please ensure that this file is available in the current working directory.
> ######time:                   0, Dump start######
> 	******START TO LOAD PROGRAM******
> 
> run: Time (s): cpu = 00:00:13 ; elapsed = 00:01:02 . Memory (MB): peak = 1061.883 ; gain = 0.000

**Comment by shenfanML** [comment]
Thanks
