### ISSUE TITLE
请问平头哥的FPGA开发板在哪里可以买得到？

### ISSUE THREAD

**Issue by shenfanML** [T-head-Semi/wujian100_open#23]
RT

**Comment by alwaysatclk** [comment]
没有必要使用特定开发板，端口信号接对就行了。

**Comment by alwaysatclk** [comment]
https://www.t-head.cn/product/mcu-platform?spm=a2ouz.12987052.0.0.469a48ab7ekQwL 可以从官网申请试试

**Comment by ARC-MX** [comment]
随便用一个开发板就可以了
