### ISSUE TITLE
请问应用程序如何下载到MCU里面？是通过JTAG接口吗

### ISSUE THREAD

**Issue by shenfanML** [T-head-Semi/wujian100_open#24]

**Comment by Dillon-Shang** [comment]
用户手册中的流程，是通过Jtag接口下载到MCU

**Comment by shenfanML** [comment]
> 
> 
> 用户手册中的流程，是通过Jtag接口下载到MCU

@Dillon-Shang 请问你所指的用户手册是这个文档吗wujian100_open Userguide v1.0.docx，那一页提到了呀？

**Comment by Dillon-Shang** [comment]
@shenfanML 我指的手册是就是项目的Readme.md，[How to use the sdk](url)章节
