### ISSUE TITLE
现在申请开发板试用，能用多长时间？

### ISSUE THREAD

**Issue by frams163com** [T-head-Semi/wujian100_open#31]
我想知道，现在申请开发板试用，能用多长时间？如果购买的话多少钱

**Comment by ARC-MX** [comment]
难道不是免费给 的吗

**Comment by frams163com** [comment]
@ARC-MX 不知道，等官方确认。不过官方貌似发个新闻就完了，可能都忘了这里了。

**Comment by ARC-MX** [comment]
我申请了  板子刚到

> @ARC-MX 不知道，等官方确认。不过官方貌似发个新闻就完了，可能都忘了这里了。

我申请了  板子刚到

**Comment by mballackh13** [comment]
> 我想知道，现在申请开发板试用，能用多长时间？如果购买的话多少钱

如果你拿到开发板，不断使用，发表一些分享，那可以一直使用下去，如果你不用了，那可以快递回来，这样可以让更多有需要的同学来充分利用资源

**Comment by frams163com** [comment]
@mballackh13 多谢回复。能够理解，虽然我指望的是能够占为己有:)
