### ISSUE TITLE
Do you need bash support? I can contribute.

### ISSUE THREAD

**Issue by framsc** [T-head-Semi/wujian100_open#40]
项目里用的shell是csh，但大部分的Linux发行版都是bash，不带csh。用 chsh 切换默认shell后，还会有各种问题。如果需要bash支持，我就开个pr. @mballackh13

**Comment by xklqj** [comment]
非常需要bash版本！当前很多命令无法直接执行。

**Comment by mballackh13** [comment]
非常欢迎，你可以修改了之后提交 @framsc
