### ISSUE TITLE
平头哥适配过的工具链有开源链接么

### ISSUE THREAD

**Issue by hongzhi2015** [T-head-Semi/wujian100_open#48]
因为 wujian100 使用 E902 cpu core，看 E902 手册，里面有平头哥的扩展指令。
从平头哥网站上下载的工具链只有二进制，没有源码。

请问哪里有平头哥适配过的工具链的源码？

**Comment by mballackh13** [comment]
https://occ.t-head.cn/community/risc_v_en/resource/zh
这里可以下载最新的工具链
