### ISSUE TITLE
几个问题，最后一个问题比较急，谢谢

### ISSUE THREAD

**Issue by sunsetillusion** [T-head-Semi/wujian100_open#51]
1.为什么CDK只有Windows版本？
2.不用synplify只用vivado可不可以？synplify实在是弄不到软件和license
3.source setup,csh的时候一直报语法错误，不太懂这个，请问怎么解决呢？报错如下
syntax error near unexpected token '('

**Comment by mballackh13** [comment]
1、目前window 开发用IDE比较多一些，linux下的话可以直接使用makefile工程
2、可以直接使用vivado，xdc需要适当修正一些
3、具体的问题可以发到群里看一下
