### ISSUE TITLE
請問CDK能支援其他openOCD相容的JTAG嗎？

### ISSUE THREAD

**Issue by piondeno** [T-head-Semi/wujian100_open#54]
我使用自己的FPGA板
想用CDK進行調試
但是沒有CKLINK
請問CDK能支援其他相同openOCD的JTAG嗎？

**Comment by Evaneee** [comment]
可以自制cklink

**Comment by UDTeD** [comment]
是的，目前为止，E902只能使用CKLink进行调试而无法使用openOCD的JTAG/SWD进行调试；
