### ISSUE TITLE
how to download tool-chain ?

### ISSUE THREAD

**Issue by BillNiz** [T-head-Semi/wujian100_open#8]
I can't find the link on web. please notice me,thanks!

**Comment by PYGC** [comment]
It only appears on the CN page

https://www.t-head.cn/file/download?spm=a2ouz.12987056.0.0.237b48abUY3PJG&file=1571624106073/T-Head%20Tools%20package.zip

![微信截图_20191022094132](https://user-images.githubusercontent.com/16513529/67254554-4163ed00-f4b0-11e9-9bf6-84b7ee2cbeef.png)

**Comment by BillNiz** [comment]
thank you.
